### ISSUE TITLE
What's the best way to get a list of emotes enabled on a given channel name?

### ISSUE THREAD

**Issue by rbaehr** [SevenTV/API#119]
What would be the preferred way for now to get a list of emotes that are enabled on a channel given the channel name such as "xqc", "hasanabi", etc?

Wondering if there's anything better than just web scraping

**Comment by AnatoleAM** [comment]
You cannot, please utilize user IDs instead. You can pass a Twitch, YouTube or Discord ID and obtain user data via `GET /v3/users/<platform>/<user id on platform>`.

**Comment by rbaehr** [comment]
Thanks, exactly what I was looking for
