### ISSUE TITLE
Bug report: Enabling an emote with multiple versions results in an older version's emote data being loaded in

### ISSUE THREAD

**Issue by b-ggs** [SevenTV/API#127]
Previously reported in https://github.com/SevenTV/EventAPI/issues/81

---

**Steps to reproduce:**
1. Open web chat with the 7TV extension enabled or a version of Chatterino with 7TV live events support
2. Enable the latest version of an emote with multiple versions (ex. [peepoChat](https://7tv.app/emotes/63438a743d1bc89e0ff9e400), which has `63438a743d1bc89e0ff9e400` as the latest version's emote ID and `60a4038db0dc46d7b43df99a` as the previous version's emote ID)
3. Use the newly enabled emote

**Expected result:**
- The latest version of the enabled emote (`63438a743d1bc89e0ff9e400` for `peepoChat`) is shown

**Actual result:**
- A previous version of the enabled emote (`60a4038db0dc46d7b43df99a` for `peepoChat`) is shown

Refreshing the page or reloading emotes on Chatterino will load in the correct version of the emote.

**Tested with:**
- 7TV Chrome Extension version 2.2.3
- Chatterino2 (https://github.com/Chatterino/chatterino2/pull/4090, commit `e5bf5a58`)

https://user-images.githubusercontent.com/6130147/199657472-f0c4f26a-73bb-46ef-95de-db65b8a2494a.mp4

https://user-images.githubusercontent.com/6130147/199657466-079c5291-3bc0-4ce0-a887-d6d87167637e.mp4

---

Response from @/Nerixyz ([link](https://github.com/SevenTV/EventAPI/issues/81#issuecomment-1302579789))

It doesn't fully send the old version. The active emote is actually correct (contains the correct id), but the emote data is incorrect.

Example from above:

```jsonc
{
  "actor": {}, // shortened
  "id": "60b39e943e203cc169dfc106",
  "kind": 3,
  "pushed": [
    {
      "index": 229,
      "key": "emotes",
      "type": "object",
      "value": {
        "actor_id": "60b39e943e203cc169dfc106",
        "data": {
          "animated": true,
          "flags": 0,
          "host": {
            "files": [], // shortened
            "url": "//cdn.7tv.app/emote/60a4038db0dc46d7b43df99a"
          },
          "id": "60a4038db0dc46d7b43df99a", // this id is incorrect
          "lifecycle": 3,
          "listed": true,
          "name": "peepoChat",
          "owner": {
            "avatar_url": "//cdn.7tv.app/pp/6053853cb4d31e459fdaa2dc/a94c67d7736940feb543e42024b740ef",
            "connections": null,
            "display_name": "Laden",
            "id": "6053853cb4d31e459fdaa2dc",
            "roles": [
              "60724f65e93d828bf8858789",
              "6076a86b09a4c63a38ebe801"
            ],
            "style": {
              "color": 3319890,
              "paint": null
            },
            "username": "laden"
          }
        },
        "flags": 0,
        "id": "63438a743d1bc89e0ff9e400", // this id is correct
        "name": "peepoChat",
        "timestamp": 1667503272517
      }
    }
  ]
}
```

I think this is rather an issue on SevenTV/Api.

**Comment by TroyKomodo** [comment]
We do not plan to fix this issue on this implementation of the API.
For more info please see https://github.com/SevenTV/SevenTV/
