### ISSUE TITLE
Query for emote by name?

### ISSUE THREAD

**Issue by YungBotEmotes** [SevenTV/API#165]
Is there a way to query for emotes by name? I'm looking at the docs (https://7tv.io/docs) and the `Search Emotes` is what I'm looking to use. However, using `/emotes/emote-name` does not work as it expects an ID for that path. I also have tried `/emotes?query=emote-name` but that still is not correct.

How do I use the `/emotes` endpoint to get emotes by searching for a particular emote name?

**Comment by rnv812** [comment]
Putting query as payload also has no effect. But I found some non-null response when requested **v2**/emotes/global . What is this for?

**Comment by Back1ng** [comment]
Same thing, wont found something by request to /emotes

**Comment by emasru** [comment]
Same thing here.

I'm guessing the API is still a work in progress, but very annoying that its stated to work in the docs...

**Comment by TheNamlit** [comment]
I think it's all the Search-Endpoints atm
Getting an empty response with the `Search Users` and a 404 with the `Search Emote Sets` (saying "Unknown Route: This route is not implemented yet")

**Comment by TroyKomodo** [comment]
We do not plan to fix this issue on this implementation of the API.
For more info please see https://github.com/SevenTV/SevenTV/
