### ISSUE TITLE
Add way to update 7TV site username after change on Twitch

### ISSUE THREAD

**Issue by lilyrrose** [SevenTV/API#169]
Currently my user (id: `632f7a86609c358bd8c232ca`) shows on the 7TV site as the username `0xL1LY` even after I changed it on Twitch which as of current is the only way to login to your 7TV account.

It would be really nice to reflect that change considering that, or a way to change your username on 7TV manually.

edit: clarity

**Comment by TroyKomodo** [comment]
We do not plan to fix this issue on this implementation of the API.
For more info please see https://github.com/SevenTV/SevenTV/
