### ISSUE TITLE
change rate limit HTTP response code to 429

### ISSUE THREAD

**Issue by ike-gg** [SevenTV/API#209]
in case of rate limit api should response with 429 HTTP code, currently its 200

**Comment by ike-gg** [comment]
also happening in case of internal server errors, i think a response should be identified with 5xx code

**Comment by AnatoleAM** [comment]
Can you explain in which cases you're receiving mismatching error codes?

**Comment by ike-gg** [comment]
internal errors when hitting graphql endpoint are very rare and happen randomly, but if they occur the response body will contain an error message, however http status code will still be 200
<img width="1143" alt="Screenshot 2023-04-02 at 13 17 08" src="https://user-images.githubusercontent.com/67127723/229349581-41f2e46f-015c-4e53-8170-0f01404da815.png">

**Comment by AnatoleAM** [comment]
GraphQL does not comform to traditional HTTP status codes, as it's not apart of the REST standard. It merely uses HTTP as a transport.
