### ISSUE TITLE
Add Way in v3 API to pull list of User Emotes

### ISSUE THREAD

**Issue by ipat8** [SevenTV/API#220]
In API v2 you could call:

`https://api.7tv.app/v2/users/<user ID>/emotes ` 

and receive a JSON output of all emotes added to a user. This functionality does not seem to be present in v3. I use this functionality to maintain a list of user emotes that can be called on by chatbots.

**Comment by AnatoleAM** [comment]
`GET https://7tv.io/v3/users/{connection.platform}/{connection.id}`

See [documentation](https://7tv.io/docs).
