### ISSUE TITLE
Fix methods on https://7tv.io/v3/users/@me/profile-picture

### ISSUE THREAD

**Issue by brian6932** [SevenTV/API#226]
The value of `access-control-allow-methods` is `GET,POST,PUT,PATCH,DELETE`
However, when you send a `DELETE`, you get `Method Not Allowed`, you really should be able to `DELETE` your pfp...

**Comment by TroyKomodo** [comment]
We do not plan to fix this issue on this implementation of the API.
For more info please see https://github.com/SevenTV/SevenTV/
