### ISSUE TITLE
SearchEmotes query in v3 GraphQL API returns the same results for all pages > 25

### ISSUE THREAD

**Issue by Bejan512** [SevenTV/API#227]
Hey I originally ran across this issue while just browsing the website looking for emotes to add to my twitch channel. There's tons of emotes available, so I wanted to take a look at which ones I could possibly add. 

It came to my attention though that after I reached page 25 of the top emotes, I was not seeing any new emotes. So I went into the network inspector to try to see what was going on, and I noticed that the GraphQL request was returning the same content for each request, even with a new page number. This only happened with page numbers above 25.

**Page 23-25 showing unique emotes**
![Screen Shot 2023-09-12 at 7 09 10 AM](https://github.com/SevenTV/API/assets/47272924/8d50fd98-c966-415a-b4ce-42bdc14fbb60)
![Screen Shot 2023-09-12 at 7 09 16 AM](https://github.com/SevenTV/API/assets/47272924/d8978507-0052-4a85-879e-afe7e37ba3f7)
![Screen Shot 2023-09-12 at 7 09 21 AM](https://github.com/SevenTV/API/assets/47272924/0116573d-8250-4fcd-b560-7085230a01c5)

**Page 25+ showing duplicate emotes**
![Screen Shot 2023-09-12 at 7 09 28 AM](https://github.com/SevenTV/API/assets/47272924/cf6ef77f-a30f-4530-8645-3f90d150f8be)
![Screen Shot 2023-09-12 at 7 09 30 AM](https://github.com/SevenTV/API/assets/47272924/16380d77-da56-4c32-bd3d-acfd92738976)
![Screen Shot 2023-09-12 at 7 09 33 AM](https://github.com/SevenTV/API/assets/47272924/9ff15b7b-7151-48c5-8210-d007463602aa)
![Screen Shot 2023-09-12 at 7 09 35 AM](https://github.com/SevenTV/API/assets/47272924/31b8caf9-4e72-4990-a36b-ca6c27d5ca6a)
![Screen Shot 2023-09-12 at 7 09 36 AM](https://github.com/SevenTV/API/assets/47272924/8a528997-9703-4945-8fab-b43a1ef91264)

I also went ahead and ran the requests myself with postman to see if the behavior was the same, and it was. I could get more emotes to show up by increasing the limit per page, but the duplication behavior after page 25 did not change.

**Postman page 23-25 unique results**
![Screen Shot 2023-09-12 at 6 57 43 AM](https://github.com/SevenTV/API/assets/47272924/c11f1755-c2e5-4f5a-a9d4-3f02669fc2bf)
![Screen Shot 2023-09-12 at 6 57 55 AM](https://github.com/SevenTV/API/assets/47272924/f288df78-57e8-4c51-a66b-c9bea58f4383)
![Screen Shot 2023-09-12 at 6 58 03 AM](https://github.com/SevenTV/API/assets/47272924/6b2fe5c9-ab13-42fa-bf8e-748981d93117)

**Postman page 25+ duplicate results**
![Screen Shot 2023-09-12 at 6 58 08 AM](https://github.com/SevenTV/API/assets/47272924/7977e0e6-832f-4066-b4d3-75eecb913c79)
![Screen Shot 2023-09-12 at 6 58 32 AM](https://github.com/SevenTV/API/assets/47272924/a5fad2cf-2299-41d0-84a0-a55c7385385f)
![Screen Shot 2023-09-12 at 6 58 42 AM](https://github.com/SevenTV/API/assets/47272924/c5c95eb4-eedc-4e02-975a-8ed0c6b95fdc)
![Screen Shot 2023-09-12 at 6 58 50 AM](https://github.com/SevenTV/API/assets/47272924/2ebf0553-946c-4334-a367-5cd692e81ec9)

I'd go over the API myself to see if I could find the issue, but I'm limited on time and not very familiar with Go.

Thanks to anyone who takes a look at this!

**Comment by TroyKomodo** [comment]
We do not plan to fix this issue on this implementation of the API.
For more info please see https://github.com/SevenTV/SevenTV/
