### ISSUE TITLE
Is version 2 of the API still supported?

### ISSUE THREAD

**Issue by jakubbloksa** [SevenTV/API#232]
Hey there, I just noticed that all of our integrations for 7TV API v2 stopped working. I can see some "documentation" for v3, but can't see any info about migration or anything specific to help me actually use it. I looked here https://7tv.io/docs

Are there any notes about this?
All we need is to access 
```https://api.7tv.app/v2/emotes/global```
and 
```https://api.7tv.app/v2/users/{twitchUserId}/emotes```

Previously it was really easy just be calling GET for these two endpoints. How to migrate this as easily as possible?

**Comment by S0und** [comment]
> https://api.7tv.app/v2/emotes/global

new: `https://7tv.io/v3/emote-sets/global`

> https://api.7tv.app/v2/users/{twitchUserId}/emotes

new: `https://7tv.io/v3/users/{platform}/{user.id}`

platform: `twitch`, `youtube`, `discord`
