### ISSUE TITLE
[BUG] `/config/extension(-nightly)?` report the wrong version

### ISSUE THREAD

**Issue by gagbo** [SevenTV/API#236]
As of right now, the response to https://7tv.io/v3/config/extension is

```
{"version":"3.0.9","overrides":[],"compatibility":[{"id":["ajopnjidmegmdimjlfnijceegpefgped","firefox@betterttv.net"],"issues":[{"platform":null,"severity":"NOTE","message":"7TV supports BetterTTV emotes by default"},{"platform":null,"severity":"DUPLICATE_FUNCTIONALITY","message":"A significant amount of functionality from this extension is also in 7TV. While there is no known immediate clashing with this extension, such redundancy may decrease performance"}]},{"id":["fadndhdgpmmaapbmfcknlfgcflmmmieb","frankerfacez@frankerfacez.com"],"issues":[{"platform":null,"severity":"NOTE","message":"7TV supports FrankerFaceZ emotes by default. This extension is compatibility-tested by our team. However, many of its features may currently be unavailable. We are working on improving integration."}]},{"id":["fooolghllnmhmmndgjiamiiodkpenpbb"],"issues":[{"platform":null,"severity":"BAD_PERFORMANCE","message":"This extension attempts to hook the chat input box, which is partially prevented by 7TV. This leads to severe lag spikes. Please consider switching to a different password manager"},{"platform":null,"severity":"WARNING","message":"Our analysis of this extension revealed that it's highly obfuscated and appears to be extremely inefficient"}]},{"id":["ipnllhnoiiclnoonckahfcpahgehgdgb"],"issues":[{"platform":null,"severity":"CLASHING","message":"This extension is wholly incompatible with 7TV's high-performance chat and breaks layout"}]},{"id":["bhplkbgoehhhddaoolmakpocnenplmhf","twitch5@coolcmd"],"issues":[{"platform":null,"severity":"WARNING","message":"7TV cannot function with this extension because it runs inside its own isolated context. Please disable it."}]}]}
```

On both Firefox and Edge (wanted to test a non-Firefox browser because of the issues with extension distribution). Note that the endpoint reports the `3.0.9` version, although the most recent stable is `3.0.16`. This is a bit misleading, because that means the website https://7tv.app/ reports the wrong versions on the downloads buttons

![The 7tv.app website with emphasis on the Download Extension button advertising the wrong version](https://github.com/SevenTV/API/assets/10496163/b9476126-6ef0-49de-9511-15a8adf95460)

This is a bit misleading and led me to believe I was up to date when I wasn't (I'm using Firefox so I assume I have to install the extension manually from the website). It looks like the extension versions are coming from a mongo read, I assume that the CI on the extension should update it automatically but doesn't, or it's a manual update to do? **Note that hitting Download here downloads the actual latest version, so it's really just cosmetic**

**Comment by TroyKomodo** [comment]
The version is wrong, however your extension is always auto-updated.
