### ISSUE TITLE
Users with Discord connections are getting Discord API numbers (0 by default now) appended with an `_` to their 7TV `username`s

### ISSUE THREAD

**Issue by brian6932** [SevenTV/API#248]
_This wasn't voluntary, their names were automatically changed, not on connection link, but all at once_
![](https://github.com/SevenTV/API/assets/18603393/84341ef9-7ce8-4c4f-a90c-1d0645f03b94)
Some examples, using the following query
```gql
{user(id:$UserID){connections{id platform username}username}}
```

<details>
	<summary>61388d575bbacadc3386a40e</summary>

```json
{
	"data": {
		"user": {
			"connections": [
				{
					"id": "313260532671184896",
					"platform": "DISCORD",
					"username": "dispersal#0"
				},
				{
					"id": "460691477",
					"platform": "TWITCH",
					"username": "augustcelery"
				}
			],
			"username": "dispersal_0"
		}
	}
}
```

</details>

<details>
	<summary>60a536d1ac08622846bced71</summary>

```json
{
	"data": {
		"user": {
			"connections": [
				{
					"id": "UCaxo5bUH82K6q7jkGc-FdCA",
					"platform": "YOUTUBE",
					"username": "UCaxo5bUH82K6q7jkGc-FdCA"
				},
				{
					"id": "156499675497627648",
					"platform": "DISCORD",
					"username": "marcfryd#0"
				},
				{
					"id": "44710465",
					"platform": "TWITCH",
					"username": "marcfryd"
				},
				{
					"id": "29770",
					"platform": "KICK",
					"username": "marc"
				}
			],
			"username": "marcfryd_0"
		}
	}
}
```

</details>

<details>
	<summary>6150811420eaf897465a7cfd</summary>

```json
{
	"data": {
		"user": {
			"connections": [
				{
					"id": "69966",
					"platform": "KICK",
					"username": "suko"
				},
				{
					"id": "930642795235000391",
					"platform": "DISCORD",
					"username": "SukoXI#0507"
				},
				{
					"id": "504059939",
					"platform": "TWITCH",
					"username": "sukoxi"
				}
			],
			"username": "suko_0736"
		}
	}
}
```

</details>

**Comment by AnatoleAM** [comment]
Works as intended. Usernames are updated to reflect the user's first connection, at this time non-Twitch connections have extra numbers appended to avoid collision; this is a temporary measure until the phasing out of on-platform usernames altogether.

**Comment by brian6932** [comment]
> Usernames are updated to reflect the user's first connection

I'm trying to say that wasn't all their first connections, maybe they disconnected their connection at some point, and then reconnected, which caused a change in order, but initially a lot of their accounts were Twitch created afaik, as they previously didn't have Discord names.
This had some unintended effects for people.
