### ISSUE TITLE
Merging multiple origin sets does not work correctly

### ISSUE THREAD

**Issue by 0xb0bba** [SevenTV/API#253]
When using multiple origin sets with conflicting emote names they do not get merged correctly.

Example Set 1 containing emotes:
A
B
C
D

Example set 2 containing variants of some of these emotes:
A
B
C

When adding both sets as an origin set to a new empty set the resulting set should have each emote once. Instead the resulting set will have the expected amount of items but there will be duplicates and some emotes go missing.
e.g. the resulting set might look like
A
A
B
C

where emote D has vanished

I've set up an example of this here
https://7tv.app/users/643599800fe566f611c49fcd
Clueless appears twice and COPIUM has gone missing

**Comment by TroyKomodo** [comment]
Emote set origins are experimental and being removed in the newer rewrite of the API in favor of allowing multiple emote sets to be enabled at the same time, with some priority system. (like minecraft resource packs)

Please see https://github.com/seventv/seventv for more info.
