### ISSUE TITLE
Emotes no longer reflect the set count nor channels using the emotes

### ISSUE THREAD

**Issue by LauraRozier** [SevenTV/API#254]
Since a backend maintenance I can't remember the exact date of, emotes seem to no longer update the number of channels they have been enabled for nor return a list of channels using the emotes.

When adding an emote to a set `mutation ChangeEmoteInSet` is sent to the GQL twice, probably to fix an issue where it wouldn't always do this on the first attempt in the past?
![image](https://github.com/SevenTV/API/assets/12035362/04657ccb-c13f-4b20-89c9-b1cb350211e6)

After checking the emote's count and channels it still shows 0 for a fresh emote (Even ones that have been up there since at least December 5th).
![image](https://github.com/SevenTV/API/assets/12035362/b9e9376e-d777-416e-9227-dd2e797f61c2)

When checking the GQL in the network logging of the devtools the count stats at 0 for this specific emote
![image](https://github.com/SevenTV/API/assets/12035362/20d93827-9ad8-4d94-a40b-dfdc8ebd3ce5)
![image](https://github.com/SevenTV/API/assets/12035362/6b72f98d-b59e-49ef-8702-dc8d747fc990)

When checking an older, more popular emote I do see a number, but this also won't update anymore and there is also no list channels currently using the emote (Also activity seems to be missing here).
![image](https://github.com/SevenTV/API/assets/12035362/902455b9-5106-4172-86c4-243ee116a06a)
![image](https://github.com/SevenTV/API/assets/12035362/cb21f704-ed3b-443a-8213-7ed2b8e54375)
![image](https://github.com/SevenTV/API/assets/12035362/808b5a92-f58a-4e7f-b0b9-6d75a4220702)
![image](https://github.com/SevenTV/API/assets/12035362/beb0432f-3406-46af-8ab0-97b690739cf8)
![image](https://github.com/SevenTV/API/assets/12035362/9b83c0db-e767-4c7d-8f36-b4e336799bac)

Dec. 5th emote ID: 656f22bf993668f0217a8e5d
Old emote ID: 6437c75aaa32f7b42f3f4273

I did try using different browsers, different internet connections (also meaning different PCs like my home computers and office laptop), with and without a PiHole in the network, using different DNS providers and looking at it without being logged in.

I know of at least a couple dozen users that seem to be experiencing the same problem but feel afraid to report it in Discord for each their own reason, so I hope this issue reaches you well. :)

I tried looking at the repo's code but GQL in GoLang is just not my cuppa-tea.

**Comment by olegsvs** [comment]
Same here

**Comment by TroyKomodo** [comment]
The channel count updating was disabled because its "too expensive to compute", it will be re-enabled again once we finish cleaning this codebase.

Please see https://github.com/seventv/seventv for more info.
