### ISSUE TITLE
[IDEA] using api to add/remove emotes

### ISSUE THREAD

**Issue by TastyPommesLul** [SevenTV/API#255]
the ability to make a twitch bot that listens to a command (!emoterequest [link/id]) and then it adds that emote (if the tags are ok (being able to exclude tags (for example nsfw))).

**Comment by TroyKomodo** [comment]
This is the old API and is being rewritten in our monorepo.

Please see https://github.com/seventv/seventv for more info.

No feature requests will go into this repo.
