### ISSUE TITLE
[BUG] Nickname Color Bug in Twitch Chat on Windows 11 Edge

### ISSUE THREAD

**Issue by misikovich** [SevenTV/API#256]
**Describe the issue**
_**The colored 7tv subscriber nickname occasionally gets replaced with the stock basic from Twitch when sending messages in the chat.**_
The problem is not client-side (imo), because I can see same thing at streamers side in stream picture. Also I can see that other 7tv subscribers are also having same issue.

**Where does the issue happen**
Website - twitch.tv

**Steps to Reproduce**

1. Open Microsoft Edge browser version 120.0.2210.133.
2. Navigate to the twitch.tv website.
3. Log in to your account.
4. Verify that you are a 7tv subscriber with a colored nickname.
5. Enter a chat room.
6. Send a message in the chat.

**Expected Behavior**
The expectation is to consistently see the fancy colored 7tv subscriber nickname every time a message is sent in the chat.

**Environment**

OS: Windows 11
Web Browser: Microsoft Edge 120.0.2210.133

**Comment by TroyKomodo** [comment]
This is the old API and is being rewritten in our monorepo.

Please see https://github.com/seventv/seventv for more info.

- This bug should also be fixed.
